theme: jekyll-theme-giellalt
title: Dictionary for Norsk Bokmål ⇒ Lule Saami
description: An electronic dictionary from Norsk Bokmål to Lule Saami

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
