remote_theme: giellalt/jekyll-theme-giellalt@main
title: Dictionary for Norsk Bokmål ⇒ Lule Saami
description: An electronic dictionary from Norsk Bokmål to Lule Saami
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jemoji

defaults:
  - scope: { path: "" }
    values:
      layout: minimal
